var wordle=new Wordle,wordle_solver=new WordleSolver(wordle);document.getElementById("reset_button").addEventListener("click",function(a){a.preventDefault();wordle_solver.initialize()});window.addEventListener("DOMContentLoaded",function(a){document.getElementById("guess").innerText=wordle_solver.guess});document.getElementById("reset_button").addEventListener("click",function(a){a.preventDefault();document.getElementById("guess").innerText=wordle_solver.guess});
document.getElementById("change_button").addEventListener("click",function(a){a.preventDefault();a=document.getElementById("guess_input").value.toLowerCase();wordle_solver.wordle.valid_guesses.includes(a)?(wordle_solver.guess=a,document.getElementById("guess").innerText=wordle_solver.guess,document.getElementById("guess_input").value="",document.getElementById("guess_input").classList.remove("is-danger")):document.getElementById("guess_input").classList.add("is-danger")});
document.getElementById("reset_button").addEventListener("click",function(a){a.preventDefault();document.getElementById("guess_input").value="";document.getElementById("guess_input").classList.remove("is-danger")});var status="";
document.getElementById("solve_button").addEventListener("click",function(a){a.preventDefault();status.length!==wordle_solver.guess.length?document.getElementById("status_input").classList.add("is-danger"):(a.target.classList.add("is-loading"),requestAnimationFrame(function(){requestAnimationFrame(function(){wordle_solver.solve(status);document.getElementById("guess").innerText=wordle_solver.guess;document.getElementById("valid_solutions").innerText=wordle_solver.wordle.valid_solutions.length;status=
"";document.getElementById("status_input").value="";document.getElementById("status_input").classList.remove("is-danger");a.target.classList.remove("is-loading")})}))});document.getElementById("reset_button").addEventListener("click",function(a){a.preventDefault();status="";document.getElementById("status_input").value="";document.getElementById("status_input").classList.remove("is-danger")});
document.getElementById("correct_button").addEventListener("click",function(a){a.preventDefault();status+="1";document.getElementById("status_input").value+="\ud83d\udfe9"});document.getElementById("present_button").addEventListener("click",function(a){a.preventDefault();status+="2";document.getElementById("status_input").value+="\ud83d\udfe8"});
document.getElementById("absent_button").addEventListener("click",function(a){a.preventDefault();status+="3";document.getElementById("status_input").value+="\u2b1b"});
document.getElementById("delete_button").addEventListener("click",function(a){a.preventDefault();status=status.slice(0,-1);document.getElementById("status_input").value="";for(a=0;a<status.length;a++)"1"===status[a]?document.getElementById("status_input").value+="\ud83d\udfe9":"2"===status[a]?document.getElementById("status_input").value+="\ud83d\udfe8":document.getElementById("status_input").value+="\u2b1b"});
document.getElementById("resolve_button").addEventListener("click",function(a){a.preventDefault();a.target.classList.add("is-loading");requestAnimationFrame(function(){requestAnimationFrame(function(){wordle_solver.resolve();document.getElementById("guess").innerText=wordle_solver.guess;document.getElementById("valid_solutions").innerText=wordle_solver.wordle.valid_solutions.length;a.target.classList.remove("is-loading")})})});
window.addEventListener("DOMContentLoaded",function(a){document.getElementById("valid_solutions").innerText=wordle_solver.wordle.valid_solutions.length});document.getElementById("reset_button").addEventListener("click",function(a){a.preventDefault();document.getElementById("valid_solutions").innerText=wordle_solver.wordle.valid_solutions.length});
window.addEventListener("DOMContentLoaded",function(a){wordle_solver.wordle.is_hard_mode?document.getElementById("is_hard_mode_checkbox").checked=!0:document.getElementById("is_hard_mode_checkbox").checked=!1});document.getElementById("is_hard_mode_checkbox").addEventListener("change",function(a){wordle_solver.wordle.set_is_hard_mode(a.target.checked)});
document.getElementById("reset_button").addEventListener("click",function(a){wordle_solver.wordle.is_hard_mode?document.getElementById("is_hard_mode_checkbox").checked=!0:document.getElementById("is_hard_mode_checkbox").checked=!1});