version: '3'
services:
  github-pages:
    build: ./
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html/
    working_dir: /var/www/html/
    command: bash -c 'npm install && nginx -g "daemon off;"'